# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:

- task: FileTransform@2
  inputs:
    folderPath: '$(System.DefaultWorkingDirectory)/src'
    jsonTargetFiles: 'config.*'

- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install'

- script: |
    npm run publish
  displayName: npm run publish

- script: |
    npm run build-designer
  displayName: npm run build-designer

- task: PublishPipelineArtifact@1
  inputs:
    path: $(System.DefaultWorkingDirectory)/dist/website
    artifact: ApiPortal

- task: PublishPipelineArtifact@1
  inputs:
    path: $(System.DefaultWorkingDirectory)/dist/designer
    artifact: ApiDesigner